### ISSUE TITLE
Firewall blocks port 80.

### ISSUE THREAD

**Issue by svdmitrij** [simtechdev/smtk-devbox#10]
On ```ubuntu 14.04 4.5.0-040500-generic #201603140130 SMP Mon Mar 14 05:32:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux``` host the box's firewall rules is set to block incoming requests to port 80 after provisioning.

The rules are:
```
sudo iptables -L -n -v
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2617  458K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           state RELATED,ESTABLISHED 
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0           
  211 12660 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0           
   51  2244 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           state NEW tcp dpt:22 
   42  8575 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited 

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0           reject-with icmp-host-prohibited 

Chain OUTPUT (policy ACCEPT 2049 packets, 235K bytes)
 pkts bytes target     prot opt in     out     source               destination
```

config.yml:
```
---
environment:
  sites:
    devsite.smtk.dev:
      root: "/var/www/html/devsite.smtk.dev"
      host_names:
        - devsite.smtk.dev

  databases:
    mariadb:
      example:
        user: "root"
        password: "password"

  php:
    version: 5.6

vms:
  centos6-x64:
    box: "simtechdev/centos6-x64"
    ip: 10.0.0.10
    shared:
      - "shared:/var/www/html"

provision:
  salt:
    minion_config: "provision/salt/_minion/minion.conf"

```
